export const DUMMY_MESSAGES = [
    {
        id: '1',
        username: 'Fredel METONOU',
        avatar: require('../../assets/fredel.png'),
        lastMessage: 'Super ! On se voit demain alors ? 😊',
        time: '10:30',
        unread: 2,
        online: true,
    },
    {
        id: '2',
        username: 'Boris ADONON',
        avatar: require('../../assets/boris.png'),
        lastMessage: "J'ai partagé les photos de la soirée !",
        time: '09:15',
        unread: 0,
        online: true,
    },
    {
        id: '3',
        username: 'ATCHO Iovann',
        avatar: require('../../assets/iovann.png'),
        lastMessage: 'Merci pour ton aide !',
        time: 'Hier',
        unread: 0,
        online: false,
    },
    {
        id: '4',
        username: 'TOSSOUDJEDE Castro',
        avatar: require('../../assets/lambo.png'),
        lastMessage: 'On pourrait organiser quelque chose ce weekend ?',
        time: 'Hier',
        unread: 1,
        online: false,
    },
];